name: Publish Docker Container on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish-test:
    runs-on: ubuntu-latest

    steps:
      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nestjs
        run: npm i -g @nestjs/cli

      - name: Build and tag Docker image
        run: |
          DOCKER_IMAGE_VERSION=${{ github.ref_name }} npm run package:test
          
      - name: Push Docker image to registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/poemia:${{ github.ref_name }}

      - name: Logout from Docker registry
        run: docker logout your.docker.registry.url
